### ISSUE TITLE
can't produce a FormStep !!!!

### ISSUE THREAD

**Issue by dariosalviwork** [ResearchStack/ResearchStack#152]
I have a problem with this FormStep:
```
FormStep colGucoStep = new FormStep("cholesterolHdlSystolic", "Cholesterol & Glucose", "");
QuestionStep cholesterolStep = new QuestionStep("heartAgeDataTotalCholesterol", "Total Cholesterol", new IntegerAnswerFormat(80, 400));
QuestionStep HDLcholesterolStep = new QuestionStep("heartAgeDataHdl", "HDL Cholesterol", new IntegerAnswerFormat(10, 140));
QuestionStep LDLcholesterolStep = new QuestionStep("heartAgeDataLdl", "LDL Cholesterol (optional)", new IntegerAnswerFormat(0, 1000));
QuestionStep glucoseStep = new QuestionStep("heartAgeDataBloodGlucose", "Fasting Blood Glucose (optional)", new DecimalAnswerFormat(0, 500));
colGucoStep.setFormSteps(cholesterolStep, HDLcholesterolStep, LDLcholesterolStep, glucoseStep);
colGucoStep.setOptional(false);
steps.add(colGucoStep);
```

the exception it produces:

```
Caused by: java.lang.NoSuchMethodException: <init> [class org.researchstack.backbone.step.Step, class org.researchstack.backbone.result.StepResult]
at java.lang.Class.getConstructor(Class.java:531)
at java.lang.Class.getConstructor(Class.java:495)
at org.researchstack.backbone.ui.step.body.FormBody.createStepBody(FormBody.java:101)
at org.researchstack.backbone.ui.step.body.FormBody.getBodyView(FormBody.java:53) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.onCreateBody(SurveyStepLayout.java:246) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initializeStep(SurveyStepLayout.java:126) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initialize(SurveyStepLayout.java:85) 
at org.researchstack.backbone.ui.ViewTaskActivity.getLayoutForStep(ViewTaskActivity.java:131) 
at org.researchstack.backbone.ui.ViewTaskActivity.showStep(ViewTaskActivity.java:111) 
at org.researchstack.backbone.ui.ViewTaskActivity.showNextStep(ViewTaskActivity.java:88) 
at org.researchstack.backbone.ui.ViewTaskActivity.onExecuteStepAction(ViewTaskActivity.java:232) 
at org.researchstack.backbone.ui.ViewTaskActivity.onSaveStep(ViewTaskActivity.java:220) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.onNextClicked(SurveyStepLayout.java:302) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.lambda$onLayoutCreated$32(SurveyStepLayout.java:196) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.access$lambda$0(SurveyStepLayout.java) 
at org.researchstack.backbone.ui.step.layout.SurveyStepLayout$$Lambda$1.call(Unknown Source) 
at rx.Observable$27.onNext(Observable.java:7928) 
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) 
at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:24) 
at android.view.View.performClick(View.java:5254) 
```

please help!

**Comment by dariosalviwork** [comment]
this in the end worked. Don't ask me how.
