### ISSUE TITLE
nasty IOException when app goes background

### ISSUE THREAD

**Issue by dariosalviwork** [ResearchStack/ResearchStack#232]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.researchstack.skin.task.SmartSurveyTask)

**Comment by wdziemia** [comment]
Would you happen to have the full stack trace ? If not steps to reproduce would be great.

**Comment by notronwest** [comment]
Dario,

What should we be looking for from the apps perspective to know that we are potentially experiencing this issue?

**Comment by dariosalviwork** [comment]
to reproduce it:

start a survey (any would do)
put the app in background

stack trace:

```
FATAL EXCEPTION: main
Process: uk.ac.ox.ibme.myheartcounts, PID: 15183
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.researchstack.skin.task.SmartSurveyTask)
    at android.os.Parcel.writeSerializable(Parcel.java:1394)
    at android.os.Parcel.writeValue(Parcel.java:1341)
    at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
    at android.os.Bundle.writeToParcel(Bundle.java:1034)
    at android.os.Parcel.writeBundle(Parcel.java:669)
    at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3270)
    at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4385)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
 Caused by: java.io.NotSerializableException: java.util.AbstractList$SubAbstractListRandomAccess
    at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
    at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
    at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
    at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
    at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
    at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
    at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
    at android.os.Parcel.writeSerializable(Parcel.java:1389)
    at android.os.Parcel.writeValue(Parcel.java:1341) 
    at android.os.Parcel.writeArrayMapInternal(Parcel.java:644) 
    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
    at android.os.Bundle.writeToParcel(Bundle.java:1034) 
    at android.os.Parcel.writeBundle(Parcel.java:669) 
    at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3270) 
    at android.app.ActivityThread$StopInfo.run(ActivityThread.java:4385) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:145) 
    at android.app.ActivityThread.main(ActivityThread.java:6837) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```

**Comment by wdziemia** [comment]
excellent thank you! Will take a look

**Comment by mikecarroll** [comment]
@dariosalviwork Closing this. Please re-open if not actually fixed.
