### ISSUE TITLE
DecimalConstraints causes crash

### ISSUE THREAD

**Issue by crayne** [ResearchStack/ResearchStack#240]
Here is a JSON step definition:
````
{
            "guid": "db8d54db-c00e-4203-af71-2701253aa9e9",
            "identifier": "med1_dose",
            "type": "SurveyQuestion",
            "prompt": "What is your main medicine usual dose?",
            "detail": "Enter your dose in mg (or in units for Insulin)",
            "constraints": {
                "dataType": "decimal",
                "rules": [],
                "minValue": 0,
                "type": "DecimalConstraints"
            },
            "uiHint": "numberfield"
        }
````
This crashes my app.  I looked at SmartSurveyTask.java:
````
    private AnswerFormat from(Context context, TaskModel.ConstraintsModel constraints)
    {
        AnswerFormat answerFormat;
        String type = constraints.type;
        if(type.equals("BooleanConstraints"))
        {
            answerFormat = new BooleanAnswerFormat(context.getString(R.string.rsb_yes),
                    context.getString(R.string.rsb_no));
        }
        else if(type.equals("MultiValueConstraints"))
        {
            AnswerFormat.ChoiceAnswerStyle answerStyle = constraints.allowMultiple
                    ? AnswerFormat.ChoiceAnswerStyle.MultipleChoice
                    : AnswerFormat.ChoiceAnswerStyle.SingleChoice;
            answerFormat = new ChoiceAnswerFormat(answerStyle, from(constraints.enumeration));
        }
        else if(type.equals("IntegerConstraints"))
        {
            answerFormat = new IntegerAnswerFormat(constraints.minValue, constraints.maxValue);
        }
        else if(type.equals("TextConstraints") || type.equals("StringConstraints"))
        {
            answerFormat = new TextAnswerFormat();
            boolean multipleLines = constraints.multipleLines;
            ((TextAnswerFormat) answerFormat).setIsMultipleLines(multipleLines);
        }
        else if(type.equals("DateConstraints"))
        {
            answerFormat = new DateAnswerFormat(AnswerFormat.DateAnswerStyle.Date);
        }
        else
        {
            answerFormat = new UnknownAnswerFormat();
        }
        return answerFormat;
    }
````
I notice that the code doesn't check for "DecimalConstraints" and the method returns an UnknownAnswerFormat, so it is likely that the bug is related to that.

**Comment by wdziemia** [comment]
Would you happen to have the stacktrace of the crash?

**Comment by crayne** [comment]
````
stack.diabetes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: org.researchstack.diabetes, PID: 18032
                                                                            rx.exceptions.OnErrorNotImplementedException: java.lang.NoSuchMethodException: <init> [class org.researchstack.backbone.step.Step, class org.researchstack.backbone.result.StepResult]
                                                                                at rx.Observable$27.onError(Observable.java:8566)
                                                                                at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                                at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                                at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
                                                                                at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:24)
                                                                                at android.view.View.performClick(View.java:4438)
                                                                                at android.view.View$PerformClick.run(View.java:18422)
                                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:136)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class org.researchstack.backbone.step.Step, class org.researchstack.backbone.result.StepResult]
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.createStepBody(SurveyStepLayout.java:200)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initStepBody(SurveyStepLayout.java:176)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initializeStep(SurveyStepLayout.java:119)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initialize(SurveyStepLayout.java:83)
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.getLayoutForStep(ViewTaskActivity.java:132)
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.showStep(ViewTaskActivity.java:112)
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.showNextStep(ViewTaskActivity.java:89)
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.onExecuteStepAction(ViewTaskActivity.java:240)
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.onSaveStep(ViewTaskActivity.java:228)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.onNextClicked(SurveyStepLayout.java:225)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.lambda$initStepLayout$0(SurveyStepLayout.java:130)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.access$lambda$0(SurveyStepLayout.java)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout$$Lambda$1.call(Unknown Source)
                                                                                at rx.Observable$27.onNext(Observable.java:8571)
                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
                                                                                at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:24) 
                                                                                at android.view.View.performClick(View.java:4438) 
                                                                                at android.view.View$PerformClick.run(View.java:18422) 
                                                                                at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.NoSuchMethodException: <init> [class org.researchstack.backbone.step.Step, class org.researchstack.backbone.result.StepResult]
                                                                                at java.lang.Class.getConstructorOrMethod(Class.java:472)
                                                                                at java.lang.Class.getConstructor(Class.java:446)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.createStepBody(SurveyStepLayout.java:195)
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initStepBody(SurveyStepLayout.java:176) 
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initializeStep(SurveyStepLayout.java:119) 
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.initialize(SurveyStepLayout.java:83) 
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.getLayoutForStep(ViewTaskActivity.java:132) 
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.showStep(ViewTaskActivity.java:112) 
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.showNextStep(ViewTaskActivity.java:89) 
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.onExecuteStepAction(ViewTaskActivity.java:240) 
                                                                                at org.researchstack.backbone.ui.ViewTaskActivity.onSaveStep(ViewTaskActivity.java:228) 
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.onNextClicked(SurveyStepLayout.java:225) 
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.lambda$initStepLayout$0(SurveyStepLayout.java:130) 
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout.access$lambda$0(SurveyStepLayout.java) 
                                                                                at org.researchstack.backbone.ui.step.layout.SurveyStepLayout$$Lambda$1.call(Unknown Source) 
                                                                                at rx.Observable$27.onNext(Observable.java:8571) 
                                                                                at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139) 
                                                                                at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:24) 
                                                                                at android.view.View.performClick(View.java:4438) 
                                                                                at android.view.View$PerformClick.run(View.java:18422) 
                                                                                at android.os.Handler.handleCallback(Handler.java:733) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                                at android.os.Looper.loop(Looper.java:136) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
````
