### ISSUE TITLE
Join Button Exception

### ISSUE THREAD

**Issue by anitadesai** [ResearchStack/ResearchStack#257]
I am making an app that I started from extending skin and taking parts from SampleApp, not directly from SampleApp. I've got everything in onboarding working, and I've created the SignUp task. Whenever I click the join button I get the following exception:

>06-09 17:40:11.168 11753-11753/org.dihi.rfa.cancercoach E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: org.dihi.rfa.cancercoach, PID: 11753
                                                                          java.lang.IllegalArgumentException: Expected receiver of type org.researchstack.skin.ui.OnboardingActivity, but got android.support.v7.widget.TintContextWrapper
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at android.view.View$DeclaredOnClickListener.onClick(View.java:4460)
                                                                              at android.view.View.performClick(View.java:5226)
                                                                              at android.view.View$PerformClick.run(View.java:21266)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:168)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5845)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

I'm having difficulties finding the issue since it doesn't reference any classes in my project or ResearchStack. Any idea what might be causing it?

**Comment by anitadesai** [comment]
This issue can be solved by changing the android support dependency version (com.android.support:appcompat-v7) to 23.2.1. My version was 23.4.0.

**Comment by mikecarroll** [comment]
Thank you for the update and report @anitadesai -- sorry we were slow to respond (was traveling), but glad you resolved this yourself! I'm sure this will help others.
