### ISSUE TITLE
app crashes on uncomplete onbaording

### ISSUE THREAD

**Issue by dariosalviwork** [ResearchStack/ResearchStack#284]
I am using the sample app example for integrating with Sage.
If I go through the registration process and I stop in the middle, I get this error:

```
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: uk.ac.ox.ibme.myheartcounts.server.UploadRequest$$Configuration
             at co.touchlab.squeaky.dao.SqueakyContext.loadGeneratedTableMapper(SqueakyContext.java:90)
             at co.touchlab.squeaky.dao.SqueakyContext.getGeneratedTableMapper(SqueakyContext.java:55)
             at co.touchlab.squeaky.dao.SqueakyContext.getDao(SqueakyContext.java:34)
             at co.touchlab.squeaky.db.sqlcipher.SqueakyOpenHelper.getDao(SqueakyOpenHelper.java:44)
             at org.researchstack.backbone.storage.database.sqlite.SqlCipherDatabaseHelper.getDao(SqlCipherDatabaseHelper.java:197)
             at uk.ac.ox.ibme.myheartcounts.server.ServerEncryptedDatabase.loadUploadRequests(ServerEncryptedDatabase.java:63)
             at uk.ac.ox.ibme.myheartcounts.MHCDataProvider.uploadPendingFiles(MHCDataProvider.java:678)
             at uk.ac.ox.ibme.myheartcounts.MHCDataProvider$3.call(MHCDataProvider.java:194)
             at uk.ac.ox.ibme.myheartcounts.MHCDataProvider$3.call(MHCDataProvider.java:188)
```

`ServerEncryptedDatabase` is the same as `BridgeEncryptedDatabase` except from the name of the class.
The `uk.ac.ox.ibme.myheartcounts.server.UploadRequest` class is defined and is a copy of the one given in the SampleApp.

**Comment by mikecarroll** [comment]
It seems that what you are missing is the `Configuration` for `UploadRequest`?

**Comment by dariosalviwork** [comment]
There no Configuration class inside that class. Not in my code nor in the Sample App or Mole Mapper.
It's like it's added dynamically.

**Comment by dariosalviwork** [comment]
It doesn't happen in the Sample App, so it must be something I am doing wrong :confused:

**Comment by dariosalviwork** [comment]
BTW, any clues?

**Comment by dariosalviwork** [comment]
OK I've got it, I was missing this line in the gradle:

`    apt 'co.touchlab.squeaky:squeaky-processor:0.4.0.0'`

**Comment by mikecarroll** [comment]
👍
