### ISSUE TITLE
SQLCipher encryption errors after RuntimeException thrown 

### ISSUE THREAD

**Issue by dukemike** [ResearchStack/ResearchStack#297]
I continue to regularly get SQLCipher encryption errors on a regular basis when the app encounters a runtime exception. Is anyone else seeing this?

```java
E/Database: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
            net.sqlcipher.database.SQLiteException: file is encrypted or is not a database: , while compiling: select count(*) from sqlite_master;
                at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
                at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
                at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
                at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:83)
                at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:49)
                at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:42)
                at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1787)
                at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1752)
                at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2427)
                at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2356)
                at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1116)
                at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1179)
                at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:162)
                at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:129)
                at co.touchlab.squeaky.db.sqlcipher.SqueakyOpenHelper.getWrappedDatabase(SqueakyOpenHelper.java:66)
                at co.touchlab.squeaky.dao.SqueakyContext.getDatabase(SqueakyContext.java:64)
                at co.touchlab.squeaky.dao.ModelDao.makeCursor(ModelDao.java:261)
                at co.touchlab.squeaky.dao.ModelDao.makeCursorResults(ModelDao.java:222)
                at co.touchlab.squeaky.dao.ModelDao.access$400(ModelDao.java:27)
                at co.touchlab.squeaky.dao.ModelDao$QueryModifiersImpl.list(ModelDao.java:203)
                at org.dihi.rfa.cancercoach.CCEncryptedDatabase.getUserVO(CCEncryptedDatabase.java:109)
                at org.dihi.rfa.cancercoach.CCDataProvider.loadUser(CCDataProvider.java:320)
                at org.dihi.rfa.cancercoach.CCDataProvider.getUser(CCDataProvider.java:438)
                at org.dihi.rfa.cancercoach.CCUiManager.getMainTabBarItems(CCUiManager.java:66)
                at org.researchstack.skin.ui.MainActivity.onCreate(MainActivity.java:56)
                at android.app.Activity.performCreate(Activity.java:6237)
                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:148)
                at android.app.ActivityThread.main(ActivityThread.java:5417)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jdkizer9** [comment]
Hi @dukemike, any luck with this? I'm running into potentially the same issue. In my case, I think that I understand what's going on, but I'm not sure how to fix it.

It seems that when I remove the pin code via StorageAccess::removePinCode (I do this when a user logs out), the database remains encrypted with the previous pass code. Thus, when we attempt to add a new pin, an exception occurs when the new encryptor instance in injected into the app database. Ideally, I'd like to wipe out the local database when the pin code is removed, but it's not apparent to me on how to go about that.

**Comment by dukemike** [comment]
@jdkizer9, I wasn't able to replicate this in the sample app so it must be something in my code. For me,  simply closing the app would get the encryption pass phases out of sync.

[`context.deleteDatabase(databaseName)`](https://developer.android.com/reference/android/content/Context.html#deleteDatabase%28java.lang.String%29) may be what you are looking for.

[http://stackoverflow.com/questions/9308827/programmaticaly-erase-data-of-a-sqlite-database-using-ormlite-library](http://stackoverflow.com/questions/9308827/programmaticaly-erase-data-of-a-sqlite-database-using-ormlite-library)

**Comment by dephillipsmichael** [comment]
I also get this crash in the app.  @jdkizer9 I think is onto something in that I noticed that it only happens after I have called removePincode. After that, when you set a new pin code, I believe the database is still encrypted with the old key, and hence the new encryption key will be inaccurate, which is what the error is stating.
