### ISSUE TITLE
can´t see video on Android 4.1

### ISSUE THREAD

**Issue by ghost** [ResearchStack/ResearchStack#339]
it seems that it can't find android.view.SurfaceView

here's the trace

```
02-01 14:05:03.540 3437-3437/? I/dalvikvm: Could not find method android.view.SurfaceView.<init>, referenced from method org.researchstack.backbone.ui.views.AssetVideoView.<init>
02-01 14:05:03.540 3437-3437/? W/dalvikvm: VFY: unable to resolve direct method 20410: Landroid/view/SurfaceView;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
02-01 14:05:03.540 3437-3437/? D/dalvikvm: VFY: replacing opcode 0x70 at 0x0002
02-01 14:05:03.552 3437-3439/? D/dalvikvm: GC_CONCURRENT freed 314K, 9% free 9598K/10439K, paused 11ms+10ms, total 23ms
02-01 14:05:03.552 3437-3437/? D/AndroidRuntime: Shutting down VM
02-01 14:05:03.552 3437-3437/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa62ff288)
02-01 14:05:03.564 3437-3437/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.ac.ox.ibme.myheartcounts/org.researchstack.backbone.ui.ViewVideoActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class org.researchstack.backbone.ui.views.AssetVideoView
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class org.researchstack.backbone.ui.views.AssetVideoView
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                     at org.researchstack.backbone.ui.ViewVideoActivity.onCreate(ViewVideoActivity.java:33)
                                                     at android.app.Activity.performCreate(Activity.java:5008)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Constructor.constructNative(Native Method)
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at org.researchstack.backbone.ui.ViewVideoActivity.onCreate(ViewVideoActivity.java:33) 
                                                     at android.app.Activity.performCreate(Activity.java:5008) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
                                                  Caused by: java.lang.NoSuchMethodError: android.view.SurfaceView.<init>
                                                     at org.researchstack.backbone.ui.views.AssetVideoView.<init>(AssetVideoView.java:119)
                                                     at org.researchstack.backbone.ui.views.AssetVideoView.<init>(AssetVideoView.java:113)
                                                     at org.researchstack.backbone.ui.views.AssetVideoView.<init>(AssetVideoView.java:107)
                                                     at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                     at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                     at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                     at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                     at org.researchstack.backbone.ui.ViewVideoActivity.onCreate(ViewVideoActivity.java:33) 
                                                     at android.app.Activity.performCreate(Activity.java:5008) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
02-01 14:05:03.568 451-664/system_process W/ActivityManager:   Force finishing activity uk.ac.ox.ibme.myheartcounts/org.researchstack.backbone.ui.ViewVideoActivity
02-01 14:05:03.572 451-664/system_process W/ActivityManager:   Force finishing activity uk.ac.ox.ibme.myheartcounts/org.researchstack.skin.ui.OnboardingActivity
02-01 14:05:04.072 451-464/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{536653e8 uk.ac.ox.ibme.myheartcounts/org.researchstack.backbone.ui.ViewVideoActivity}
```

**Comment by dephillipsmichael** [comment]
Nice find.  Looks like for some reason all the constructors of that class end up calling the API 21 only constructor, which, naturally, doesn't exist below 21.  Fixed it for you https://github.com/ResearchStack/ResearchStack/pull/340
