### ISSUE TITLE
SQLCipher incompatible with Android 7

### ISSUE THREAD

**Issue by ghost** [ResearchStack/ResearchStack#371]
At least version 3.3.1

the issue is this one: 
https://github.com/sqlcipher/android-database-sqlcipher/issues/216

version 3.5.0 should be compatible now although some issues are still open

this is my stack trace:

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libutils.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:977)
	at java.lang.System.loadLibrary(System.java:1530)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:174)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:169)
	at uk.ac.ox.ibme.myheartcounts.MyHeartCounts$1.createAppDatabaseImplementation(MyHeartCounts.java:70)
	at org.researchstack.skin.ResearchStack.init(ResearchStack.java:65)
	at uk.ac.ox.ibme.myheartcounts.MyHeartCounts.onCreate(MyHeartCounts.java:67)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5402)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

```

**Comment by dephillipsmichael** [comment]
This is fixed on the develop branch.
 
We updated to...
compile 'net.zetetic:android-database-sqlcipher:3.5.4@aar'

I'd suggest doing the same on your local copy of RS master or submitting a PR to change.

**Comment by ghost** [comment]
thanks

**Comment by riyazparasara** [comment]
Thank You So much.
