### ISSUE TITLE
"IllegalArgumentException: view must not be null" caused by PinCodeActivity

### ISSUE THREAD

**Issue by ghost** [ResearchStack/ResearchStack#383]
Hello,

I am using v 1.1.1 and I get bothered every now and then by the following exception.
It seems to be a problem of the PinCodeActivity and I have no clue of how to fix it...

```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6165)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: rx.exceptions.OnErrorNotImplementedException: view must not be null
at rx.Observable$27.onError(Observable.java:8566)
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:378)
at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:153)
at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
... 7 more
Caused by: java.lang.IllegalArgumentException: view must not be null
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:378)
at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:119)
at org.researchstack.backbone.ui.PinCodeActivity.lambda$onDataAuth$9(PinCodeActivity.java:203)
at org.researchstack.backbone.ui.PinCodeActivity.access$lambda$6(PinCodeActivity.java)
at org.researchstack.backbone.ui.PinCodeActivity$$Lambda$10.call(Unknown Source)
at rx.Observable$27.onNext(Observable.java:8571)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
... 14 more
rx.exceptions.OnErrorNotImplementedException: view must not be null
at rx.Observable$27.onError(Observable.java:8566)
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:201)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:144)
at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:378)
at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:153)
at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6165)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.IllegalArgumentException: view must not be null
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:378)
at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:119)
at org.researchstack.backbone.ui.PinCodeActivity.lambda$onDataAuth$9(PinCodeActivity.java:203)
at org.researchstack.backbone.ui.PinCodeActivity.access$lambda$6(PinCodeActivity.java)
at org.researchstack.backbone.ui.PinCodeActivity$$Lambda$10.call(Unknown Source)
at rx.Observable$27.onNext(Observable.java:8571)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
... 14 more
java.lang.IllegalArgumentException: view must not be null
at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:378)
at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:119)
at org.researchstack.backbone.ui.PinCodeActivity.lambda$onDataAuth$9(PinCodeActivity.java:203)
at org.researchstack.backbone.ui.PinCodeActivity.access$lambda$6(PinCodeActivity.java)
at org.researchstack.backbone.ui.PinCodeActivity$$Lambda$10.call(Unknown Source)
at rx.Observable$27.onNext(Observable.java:8571)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:378)
at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:340)
at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:825)
at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:153)
at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:85)
at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:215)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6165)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(Zygot
```eInit.java:778)

**Comment by ghost** [comment]
OK fixing it was easy, just a != null check.
