### ISSUE TITLE
SampleApp crash

### ISSUE THREAD

**Issue by crayne** [ResearchStack/ResearchStack#58]
Running SampleApp on Motorola Droid Razr M  4.4.2 (API 19)   -  touched "Join the Study" and app crashed.  Is app not designed to work with this (admittedly obsolete) AP version?  I (couldn't find the minimum API version in any of the AndroidManifest.xml files.

Stack trace:

03-10 16:47:54.006  22629-22629/co.touchlab.researchstack.sampleapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: co.touchlab.researchstack.sampleapp, PID: 22629
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.touchlab.researchstack.sampleapp/org.researchstack.skin.ui.SignUpTaskActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5102)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:98)
            at android.support.v7.widget.ToolbarWidgetWrapper.<init>(ToolbarWidgetWrapper.java:91)
            at android.support.v7.app.ToolbarActionBar.<init>(ToolbarActionBar.java:73)
            at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:205)
            at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:99)
            at org.researchstack.backbone.ui.ViewTaskActivity.onCreate(ViewTaskActivity.java:53)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5102)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by DP0326** [comment]
can you please share the details of fixing this issue??

**Comment by crayne** [comment]
Basically, I just replace the build.gradle with a more recent one.

**Comment by DP0326** [comment]
Hi,
Thank you for your kind reply. I am using gradle version 5.1.1 but it is
not solving the problem. Do you have any suggestion for me?

Regards
*Dilruba Parvin*
Graduate Research Assistant
Department of Electrical Engineering & Computer Science
University of Missouri
107 Naka Hall
Columbia, Missouri 65211
+1 (573) 823-3763
email: dpztv@mail.missouri.edu
dilruba.parvin0326@gmail.com

**Comment by crayne** [comment]
I am sorry.  I worked on this 3 years ago and do not recall how I fixed the problem.

**Comment by DP0326** [comment]
Thank you anyway.

On 16 Jul 2019 20:16, "Susan Crayne" <notifications@github.com> wrote:
>
> I am sorry. I worked on this 3 years ago and do not recall how I fixed
the problem.
